language: python
  python: 
    -3.5
 # command to install dependencies in the requirements file
# You can also install the coverage here to avoid it being in the requirements file
# It is important to avoid things like coverage, pep8 that are not required to run the app
install:
  - pip install -r requirements.txt
  - pip install coverage
   
 # Another command/method to run tests
script: true
  - pytest

# This returns the coverage and let's coveralls know the coverage percent. 
# Note that travis will build your system and get the coverage. 
# It cannot display, therefore coveralls becomes important to get the coverage
# You can also use after_success
after_script:
  - coveralls
 
# Using codecov to get coverage
after_success:
  - codecov
